### ISSUE TITLE
check user priv for editing experiments 

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#11]
it seems that users that lose all their priviledges (including AERPAW user), can still edit experiments they are part of and initiate development in them.

**Comment by YufengXin** [comment]
1. Allow the operator to kick off an AERPAW user.
2. When a user is deprived of the "project member" role, he can not see even the existing projects/experiments
3. The operator can deprive the "PI" role.

**Comment by YufengXin** [comment]
finished, to be deployed for further testing

**Comment by YufengXin** [comment]
A new "member" panel is added for the owner to move a user in and out of the project.
