### ISSUE TITLE
add relevant links to the documentation for the portal

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#12]
please add relevant links to the documentation for the portal - I think that this is a GA requirement. Links should explicitly be added for: (i) AERPAW main website, aerpaw.org, (ii) AERPAW wiki (link is on aerpaw.org). Please include links in Portal front page, maybe in a section just above current “Operator Tools”. Please front the links with the text “User manuals, tutorials, and other relevant documentation can be found at the following links; please refer to relevant instructions before attempting to use this Portal."

**Comment by YufengXin** [comment]
https://drive.google.com/drive/folders/1w7i-Q6Kf1rKkBgq-55Q05isUq4Bctt3Y
User manuals are being updated.

**Comment by YufengXin** [comment]
Added the new AERPAW wiki link
