### ISSUE TITLE
add a link to the acceptable use policy

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#13]
please add a link to the acceptable use policy (Ismail or Lavanya will provide the link URL once it's posted) - this is a GA requirement if I'm not wrong.

**Comment by YufengXin** [comment]
waiting for the link from NCSU

**Comment by YufengXin** [comment]
Temporarily pointing to AERPAW web

**Comment by YufengXin** [comment]
pointed to the AERPAW wiki page
