### ISSUE TITLE
add contextual help throughout the portal

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#14]
it would be nice to have contextual help throughout the portal. A relatively unobtrusive way to provide it is to have a small question mark or similar link next to each field and button with a small pop-up explaining what's supposed to go in the field or what would happen upon pressing the button.

**Comment by YufengXin** [comment]
This would be addressed in next deployment

**Comment by YufengXin** [comment]
done. can reopen if not enough.
