### ISSUE TITLE
Mail system is sometimes down

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#2]
The mail system (which for now seems crucial for the operation of the portal), seems to be down sometimes (for hours at a time last Thursday).

**Comment by YufengXin** [comment]
This email issues happens across multiple email-related functions. The emails finally arrived, only after a few hours.
Might just a transient gmail service issue, but need some test.

**Comment by YufengXin** [comment]
Might be transient. Gmail only allows <2000emails/day.
