### ISSUE TITLE
relationship between the various elements in the portal

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#3]
Regarding the overall portal, I'm still (slightly) unclear what is the relationship between the various elements in the portal. Personally, it would help a lot to have a diagram with all the important elements (users (with flags), projects, experiments, resources, operator, etc.) and their relationships (who can create and destroy what, who can recruit what, and who can see what). I guess that the whole diagram could be listed in form of bullets, but it's probably harder to follow.

**Comment by YufengXin** [comment]
Revise the object UML diagram.

**Comment by YufengXin** [comment]
<img width="1583" alt="Screen Shot 2021-08-03 at 1 57 49 PM" src="https://user-images.githubusercontent.com/7586022/128065263-ab477407-1f52-4e4b-862c-2b1baf5cc5c9.png">

**Comment by YufengXin** [comment]
Goes to issue #12 Documentation
