### ISSUE TITLE
menu items for roles

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#4]
When an “AERPAW User” has multiple roles, it is not possible for the user, once logged in, to know what role (or view for what role) they are currently in, or to change roles. (Or if it is possible, it is not obvious how to accomplish.) Please include such menu items, or other ways of accomplishing.

**Comment by YufengXin** [comment]
User's role is defined by the union of all the roles assigned.

**Comment by YufengXin** [comment]
It shows under "Accounts" -> "User Role"
