### ISSUE TITLE
project page functionality

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#5]
There seems to be some missing functionality on the "Projects" page: each project seems to have a "Join" button, but it does not seem to do anything once pressed. I'm not sure what's supposed to do - I assume that it should allow a new user join an existing project, but doesn't seem to do the trick (the owner of the project doesn't get an email or any other notification as far as I can tell).

**Comment by YufengXin** [comment]
Project joining workflow between a user and a PI. Preferably three buttons can be added in the Email body to PI to push: Yes, No, Email Reply for more information, so that the PI doesn't need to login to the portal to do these.

**Comment by YufengXin** [comment]
1. "Join" function extended based on the public and private project attributes. The proper "Join" email is sent to PI for approval.
2. The embedded Three buttons in the Email body is not trivial as it requires both API and security functions. Instead the Email body will contain a url to the project approval page in the Portal.

**Comment by YufengXin** [comment]
In addition to "Join" Emails. A new function "Message" is added under the "Account" menu, which provides a dashboard for the user to see all the emails she sent and received.
