### ISSUE TITLE
setting project/experiment privacy 

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#7]
When listing both Experiments and Projects, it may be a problem showing everybody's projects and experiments for everybody to see. It may be useful to make a flag both for projects and experiments that would allow a user to keep a project or experiment private. List the others (that don't care).

**Comment by YufengXin** [comment]
Change the default of project and experiment to be private, i.e, a user can only say own projects.

**Comment by YufengXin** [comment]
finished, to be deployed

**Comment by YufengXin** [comment]
done
