### ISSUE TITLE
remove the emulab nodes from the resources

### ISSUE THREAD

**Issue by oihawkins** [AERPAW-Platform-Control/User-Feedback#9]
please remove the emulab nodes from the resources; or confirm that anybody with an “Ops” role may do so.

**Comment by YufengXin** [comment]
The API call can be turned off.

**Comment by efu39** [comment]
Clear AERPAWGW_HOST/AERPAWGW_PORT/AERPAWGW_VERSION in .env. 
Emulab nodes then won't be listed.

**Comment by YufengXin** [comment]
Done by Erica.
